#!/usr/bin/env bash
set -e

DICTDIR=~/Documents/Dictionaries
MKXTBDIR=~/MkXTBWikiplexus/build.unix
PLIST=~/dotfiles/tools/info-plists

if(test $# -ne 2); then
    echo "Error: Invalid Parameter."
    echo "Usage: XTBook [WikiName] [Date]"
    echo "Example: XTBook jawiki 20220101"
    echo "         XTBook jaunwiki 20220101"
    echo
    echo "Your dump file must have this naming style: [WikiName]-[Date]-pages-articles.xml"
    echo "Example: jawiki-20220101-pages-articles.xml"
    exit
fi

mkdir -p ${DICTDIR}
cd ${DICTDIR}
echo "Running MkXTBWikiplexus..."
${MKXTBDIR}/MkXTBWikiplexus-bin -o $1-$2.xtbdict < $1-$2-pages-articles.xml &> /dev/null
cd $1-$2.xtbdict
echo "Running YomiGenesis..."
${MKXTBDIR}/YomiGenesis-bin < BaseNames.csv > Yomi.txt 2> /dev/null
${MKXTBDIR}/MkXTBIndexDB-bin -o Search Yomi.txt
${MKXTBDIR}/MkRax-bin -o Articles.db.rax  < Articles.db
rm -f Articles.db Yomi.txt BaseNames.csv Titles.csv
cp ${PLIST}/$1.plist info.plist
